name: GLaDOS Diagnostics

on:
  schedule:
    - cron: '0 * * * *'  # Every hour

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run GLaDOS Monitor
        run: |
          pip install requests
          python diagnostics_monitor.py
